const FETCH_PROJECTS = 'FETCHPROJECTS';
const ADD_PROJECT = 'ADD_PROJECT';
const EDIT_PROJECT = 'EDIT_PROJECT';
const DELETE_PROJECT = 'DELETE_PROJECT';
const IS_FILTER = 'IS_FILTER';
const FILTER_PROJECTS = 'FILTER_PROJECTS';

export default {
   FETCH_PROJECTS,
   ADD_PROJECT,
   EDIT_PROJECT,
   DELETE_PROJECT,
   IS_FILTER,
   FILTER_PROJECTS
}
