const FETCH_TICKETS = 'FETCHTICKETS';
const ADD_TICKET = 'ADD_TICKET';
const EDIT_TICKET = 'EDIT_TICKET';
const DELETE_TICKET = 'DELETE_TICKET';
const IS_FILTER = 'IS_FILTER';
const FILTER_TICKETS = 'FILTER_TICKETS';

export default {
   FETCH_TICKETS,
   ADD_TICKET,
   EDIT_TICKET,
   DELETE_TICKET,
   IS_FILTER,
   FILTER_TICKETS
}
