const FETCH_USERS = 'FETCH_USERS';
const LOGGED_USER = 'LOGGED_USER';
const ADD_USER = 'ADD_USER';
const EDIT_USER = 'EDIT_USER';
const DELETE_USER = 'DELETE_USER';
const IS_FILTER = 'IS_FILTER';
const FILTER_USERS = 'FILTER_USERS';

export default {
   FETCH_USERS,
   LOGGED_USER,
   ADD_USER,
   EDIT_USER,
   DELETE_USER,
   IS_FILTER,
   FILTER_USERS
}
